[build]
  command = "npm run build"
  publish = "build"  # assuming this is from inside /frontend

[context.production.environment]
  PYTHON_VERSION = "3.11.10"

[[redirects]]
  from = "/api/*"
  to = "https://opencalendar-jfsc.onrender.com/:splat"
  status = 200
  force = true
